version: "3.3"
services:
  apt-repo:
    build: .
    environment:
      - PPR_BASE
    volumes:
      - type: bind
        source: ${PPR_BASE}
        target: /home/pacstall/ppr-base
    logging:
      options:
        max-size: 10m
  web:
    image: nginx:stable-alpine
    environment:
      - PPR_BASE
    depends_on:
      - apt-repo
    volumes:
      - ${PPR_BASE}:/usr/share/nginx/html:ro
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    logging:
      options:
        max-size: 10m
  sftp:
    image: atmoz/sftp:alpine
    environment:
      - PPR_BASE
    depends_on:
      - apt-repo
    env_file:
      - .env
    volumes:
      - ${PPR_BASE}/pool:/home/sftp-pacstall/upload
      - ${PWD}/sftp-keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ${PWD}/sftp-keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ${PWD}/sftp-keys/share:/home/foo/share
    ports:
      - "420:22"
    command: sftp-pacstall:${SFTP_PASS}:::upload
    logging:
      options:
        max-size: 10m
