name: Trigger Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  parse-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Commit Description
        id: get-commit-info
        run: |
          updates_matrix="$(git log -1 --pretty=%b | awk '/^Update/,0 { if ($0 ~ /^  /) { sub(/:$/, "", $1); print $1 } }' | jq -R -s -c 'split("\n") | map(select(. != ""))')"
          echo "updated='${updates_matrix}'" >> $GITHUB_ENV

  trigger-actions:
    needs: parse-log
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Child Workflows
        if: env.updated != '[]'
        run: |
          for package in $(echo "${updated}" | jq -r '.[]'); do
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"event_type\": \"${package}\"}" \
              https://api.github.com/repos/${{ github.repository }}/dispatches
          done
